instgaram/instgaram/Controllers/PorfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using instgaram.Models;
/*
==any image is personal photo in ->          Uploads Folder
==any image is post in your profile is in -> Photopost Folder
*/

namespace instgaram.Controllers
{
    public class PorfileController : Controller
    {
        private Model db = new Model();

        public ActionResult Index()
        {
            if(Session["Userid"] == "0" && Session["Userid"]==null)
            {
                return RedirectToAction("Index", "Home");
            }
            User u =db.Users.Find(Convert.ToInt32(Session["Userid"]));
            return View(u);
        }

        //To see all person In web App and send Request
        public ActionResult allpersons()
        {
            int x = Convert.ToInt32(Session["Userid"]);
            List<User> users = db.Users.Where(
                m => m.Id != x
                ).ToList();

            List<friend_re> friend_Res = db.friend_Res.
                Where(m => m.sender1_id == x).ToList();

            foreach (var item in friend_Res)
            {
                users.Remove(item.resever);
            }
            return View(users);
        }

        //To can Add Post in Your Profile
        [HttpGet]
        public ActionResult addpost()
        {
            if (Session["Userid"] == "0" && Session["Userid"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        public ActionResult addpost(HttpPostedFileBase photo)
        {
            HttpPostedFileBase postedFile = Request.Files["photo"];
            string path = Server.MapPath("~/photopost/");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            postedFile.SaveAs(path + Path.GetFileName(postedFile.FileName));
            post post = new post();
            post.photo = "/photopost/" + Path.GetFileName(postedFile.FileName);
            post.user = db.Users.Find(Convert.ToInt32(Session["Userid"]));
            db.posts.Add(post);
            db.SaveChanges();
            return RedirectToAction("index");
        }
                
                //To see Person That send to you Request
        public ActionResult my_re()
        {
            int x = Convert.ToInt32(Session["Userid"]);
            List<friend_re> friend_Res =db.friend_Res.Where(
                m => m.sender1_id == x).ToList();
            return View(friend_Res);
        }
        public ActionResult addfriend(int? id)
        {
            friend_re friend_Re = new friend_re();

            int x = Convert.ToInt32(Session["Userid"]);
            int idi = Convert.ToInt32(id);
            try
            {
               List<friend_re> g =
                    db.friend_Res.Where(
                        m => m.sender1_id == x && m.resever1_id == idi
                        ).ToList();
                db.friend_Res.RemoveRange(g);
                db.SaveChanges();
            }
            catch
            {

            }
            friend_Re.sender1_id = x;
            friend_Re.sender = db.Users.Find(x);

            friend_Re.resever1_id = idi;
            friend_Re.resever = db.Users.Find(idi);
            
            db.friend_Res.Add(friend_Re);
            db.SaveChanges();

            return RedirectToAction("my_re");
        }
                
                //To Accept Your Request If it is Friend
        public ActionResult friendsRe()
        {
            int x = Convert.ToInt32(Session["Userid"]);
            List<friend_re> friend_Res = db.friend_Res.Where(
                m => m.sender1_id == x).ToList();
            return View(friend_Res);
        }
        public ActionResult myFreinds(int? id)
        {
            friend_re friend_Re = new friend_re();
            int x = Convert.ToInt32(Session["Userid"]);
            int idi = Convert.ToInt32(id);
            try
            {
                List<friend_re> g =
                     db.friend_Res.Where(
                         m => m.sender1_id == x && m.resever1_id == idi
                         ).ToList();
                db.friend_Res.RemoveRange(g);
                db.SaveChanges();
            }
            catch
            {

            }
            friend_Re.sender1_id = x;
            friend_Re.sender = db.Users.Find(x);

            friend_Re.resever1_id = idi;
            friend_Re.resever = db.Users.Find(idi);

            db.friend_Res.Add(friend_Re);
            db.SaveChanges();

            return RedirectToAction("friendsRe");
        }
                
                //Action Method To cancle Request
        public ActionResult cancle(int? id)
        {
            int x = Convert.ToInt32(Session["Userid"]);
            int idi = Convert.ToInt32(id);
            try
            {
                List<friend_re> g =
                   db.friend_Res.Where(
                       m => m.sender1_id == x && m.resever1_id == idi
                       ).ToList();
                db.friend_Res.RemoveRange(g);
                db.SaveChanges();

            }
            catch
            {

            }
            return RedirectToAction("my_re");
        }
                
                //Action Method To Search Person
        public ActionResult getpersons (FormCollection form)
        {
            int x = Convert.ToInt32(Session["Userid"]);
            string name = form["name"].ToString();
            List<User> users = db.Users.Where(m => m.FName == name).ToList();
            return View(users);
        }

                //To Edit Your Profile
        public ActionResult incom_requst()
        {
            int x = Convert.ToInt32(Session["Userid"]);
            List<friend_re> users =
                db.friend_Res.Where(m => m.resever1_id == x).ToList();
            return View();
        }
    }
}

instgaram/instgaram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <style>
    </style>
    <link href="~/Content/StyleForLayout.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background:#09517a;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @{if (Session["Userid"] == "0")
                    {
                        @Html.ActionLink("Instgram", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    else
                    {
                        @Html.ActionLink("Instgram", "Index", "Porfile", new { area = "" }, new { @class = "navbar-brand" })
                    }
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{ if (Session["Userid"] != "0")
                        {
                            //<li> @Html.ActionLink("Sugge", "allpersons", "porfile")</li>
                            //<li> @Html.ActionLink("Requsts", "my_re", "porfile")</li>
                            //<li> @Html.ActionLink("Followers", "friendsRe", "porfile")</li>
                            <li style="margin-left:150px;font-size:22px">
                                 @Html.ActionLink("Add Post", "addpost", "porfile")
                            </li>
                            <li style="font-size:22px;"> @Html.ActionLink("Edit Profile", "incom_requst", "porfile")</li>
                            <li style="margin-left:500px;text-decoration:none;
                                       font-size:25px;font-family:Andalus;">
                                @Html.ActionLink("LogOut", "Index", "Home")
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="bodyPages">
        @RenderBody()
    </div>

    @*<div class="container body-content">
        <footer>
            <p>&copy; @DateTime.Now.Year - Instagram Application</p>
        </footer>
    </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>